name: CI
on:
  pull_request:
    branches:
    - main

env:
  repository: EmilySeville7cfg/personal-automation-helpers

jobs:
  check-yaml:
    uses: ./.github/workflows/check-yaml.yaml
  check-markdown:
    uses: ${{ env.repository }}/github/workflows/check-markdown.yaml
    with:
      config-name: base
